spring: 
  datasource: 
     username: tdsqlsys_normal
     password: 2MYqLEKqa9gz&iaO^3IY
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://172.30.144.72:4001/ams  
  redis:
    host: localhost
    port: 6379
    password: 123456
  servlet: 
    multipart: 
      max-file-size: 200Mb
      max-request-size: 200Mb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
    prefer-ip-address: true

server: 
  port: 1111
upload: 
  serverPath: D:\\tempFile 

security:
  oauth2: 
    resource:
      id: files
      user-info-uri: http://localhost:5000/user
      prefer-token-info: false
