  
eureka: 
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
    prefer-ip-address: true
spring: 
  datasource: 
       username: tdsqlsys_normal
       password: 2MYqLEKqa9gz&iaO^3IY
       driver-class-name: com.mysql.cj.jdbc.Driver
       url: jdbc:mysql://172.30.144.72:4001/ams    
server: 
  port: 8082
security:
  oauth2: 
    resource:
      id: ams
      user-info-uri: http://localhost:5000/user
      prefer-token-info: false
